[package]
name = "p2p_client"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10.8"
byteorder = "1.5.0"
aes-gcm = "0.10.3"
x25519-dalek = "2.0.1"
tokio = { version = "1", features = ["full"] }